<? if ($this->get_type() === 'checkbox'): ?>
    <input type='checkbox' name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' data-required=\'true\'' ?><? if ($this->get_checked()) echo ' checked' ?>>
    <? if (!$this->get_inline()): ?><br /><? endif ?>
    <label for='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' class=\'required\'' ?>><?= $this->get_title() ?></label>
<? elseif ($this->get_type() === 'password'): ?>
    <label for='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' class=\'required\'' ?>><?= $this->get_title() ?></label>
    <? if (!$this->get_inline()): ?><br /><? endif ?>
    <input type='password' name='<?= $this->get_name() ?>' value='<?= $this->get_value_before_submission() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' data-required=\'true\'' ?>>
<? else: ?>
    <label for='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' class=\'required\'' ?>><?= $this->get_title() ?></label>
    <? if (!$this->get_inline()): ?><br /><? endif ?>
    <input type='text' data-type='<?= $this->get_type() ?>' value='<?= $this->get_value_before_submission() ?>' name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' data-required=\'true\'' ?>>
<? endif ?>