<? if ($this->get_type() === 'checkbox'): ?>
    <label for='<?= $this->get_name() ?>'><?= $this->get_title() ?></label>
    <input type='<?= $this->get_type() ?>' name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' required' ?><? if ($this->get_checked()) echo ' checked' ?>>
<? else: ?>
    <input type='<?= $this->get_type() ?>' name='<?= $this->get_name() ?>' id='<?= $this->get_name() ?>'<? if ($this->is_required()) echo ' required' ?><? if ($this->get_checked()) echo ' checked' ?>>
    <? if (!$this->get_inline()): ?><br /><? endif ?>
    <label for='<?= $this->get_name() ?>'><?= $this->get_title() ?></label>
<? endif ?>