<div class='flink-vc video paused' data-volume-level='high'>
    <div class="gui">
        <? if ($this->is_timelineable()): ?>
            <div class='timeline-wrapper'>
                <div class='timeline'>
                    <div class='indicator'>
                    </div>
                </div>
            </div>
        <? endif ?>
        <? if ($this->is_controlable()): ?>
            <div class='controls'>
                <button class='button play-pause'>
                    <i class='fa fa-play play'></i>
                    <i class='fa fa-pause pause'></i>
                </button>
                <div class='volume-container'>
                    <button class='button mute-unmute'>
                        <i class='fa fa-volume-high volume-high'></i>
                        <i class='fa fa-volume-low volume-low'></i>
                        <i class='fa fa-volume-xmark volume-muted'></i>
                    </button>
                    <input class='volume-slider' type='range' min='0' max='1' step='any' value='1'>
                </div>
                <div class='duration-container'>
                    <div class="current-time">0:00</div>/<div class="total-time">0:00</div>
                </div>
                <button class='button speed'>1x</button>
                <button class='button fullscreen'>
                    <i class='fa fa-expand expand'></i>
                    <i class='fa fa-compress compress'></i>
                </button>
            </div>
        <? endif ?>
    </div>
    <video src='<?= $this->get_src() ?>'<?= $this->get_autoplay() ? ' autoplay' : '' ?>></video>
</div>